from hash_algorithms import compare_hash_algoritms
from signature_algorithms import compare_signature_algorithms
from encrypt_algoritms import compare_encrypt_algoritms

compare_hash_algoritms()
compare_signature_algorithms()    
compare_encrypt_algoritms()